#parser: "@babel/eslint-parser"
parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
#  project: 'tsconfig.json'
#  warnOnUnsupportedTypeScriptVersion: false

env:
  browser: true,
  node: true

rules:
  semi: error
  no-extra-semi: warn
  quotes:
    - warn
    - single
    - avoidEscape: false
  no-unused-vars: warn
  no-undef: error
  "react/jsx-uses-react": error
  "react/jsx-uses-vars": error
  "@typescript-eslint/no-unused-vars": warn

overrides:
  - files:
      - "__tests__/**/*.{js,ts}x?"
      - "src/**/*.{test,spec}.{js,ts}x?"
    env:
      jest: true
    plugins:
      - jest
    rules:
      "jest/no-disabled-tests": "warn"
      "jest/no-focused-tests": "error"
      "jest/no-identical-title": "error"
      "jest/prefer-to-have-length": "warn"
      "jest/valid-expect": "error"

plugins:
  - react
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/eslint-plugin-tslint"
